import assert from 'node:assert/strict';
import {normalizeName,missedLetters,PracticeSequence,SetupGate,framing} from '../dist/practice.js';
assert.deepEqual(normalizeName('  Éva-Lou ’A '),[...'EVALOUA']);
for(const invalid of ['', '你好', '<script>', 'Alex123', 'A'.repeat(25)])assert.throws(()=>normalizeName(invalid));
assert.deepEqual(missedLetters([{letter:'S',correct:false},{letter:'T',correct:false},{letter:'S',correct:false},{letter:'A',correct:true},{letter:'bad',correct:false},null]),['S','T']);
assert.deepEqual(missedLetters(null),[]);
const seq=new PracticeSequence(normalizeName('Anna'));
assert(seq.match());assert.equal(seq.completed,1);assert.equal(seq.state,'release');assert(!seq.match());
for(let t=0;t<=600;t+=100)assert(!seq.release(false,t));
assert(!seq.release(true,700));assert(!seq.release(true,800));assert(!seq.release(true,1200),'Stale frames must not count as a release');
for(let t=1300;t<1600;t+=100)assert(!seq.release(true,t));assert(seq.release(true,1600));
assert.equal(seq.letter,'N');assert(seq.match());assert.equal(seq.completed,2);
assert(!seq.release(true,1700));assert(!seq.release(false,1800));assert(!seq.release(true,1900));
for(let t=2000;t<2300;t+=100)assert(!seq.release(true,t));assert(seq.release(true,2300));assert.equal(seq.letter,'N');
assert(seq.match());for(let t=2400;t<2800;t+=100)assert(!seq.release(true,t));assert(seq.release(true,2800));assert.equal(seq.letter,'A');assert(seq.match());assert.equal(seq.state,'done');assert.equal(seq.completed,4);assert(!seq.match());
const points=Array.from({length:21},(_,i)=>({x:.3+(i%4)*.08,y:.25+Math.floor(i/4)*.07,z:0}));
assert(framing(points).ok);assert(!framing(null).ok);assert(!framing(points.map(p=>({...p,x:.01}))).ok);assert(!framing(points.map(p=>({...p,x:.5+(p.x-.5)*.1,y:.5+(p.y-.5)*.1}))).ok);
const gate=new SetupGate();for(let t=0;t<700;t+=100)assert(!gate.update(points,t).ready);assert(gate.update(points,700).ready);
gate.reset();gate.update(points,0);assert(!gate.update(points,800).ready,'A stalled camera is not a steady hand');
gate.reset();gate.update(points,0);assert(!gate.update(null,100).ready);assert(!gate.update(points,200).ready);
const shifted=points.map(p=>({...p,x:p.x+.1}));assert.equal(gate.update(shifted,300).progress,0);for(let t=400;t<1000;t+=100)assert(!gate.update(shifted,t).ready);assert(gate.update(shifted,1000).ready);
console.log('Passed name validation, repeated-letter release, missed-letter filtering, and stable camera framing checks.');
